from openai import OpenAI
import os

class SmartService:
    def __init__(self):
        # 配置 OpenAI 客户端
        self.client = OpenAI(
            base_url="https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
            api_key="sk-c13d96e9c2b0486bb3a2c2ed6016e9b5"
        )
        self.model = "qwen3-max" 

    def chat(self, message: str) -> str:
        """
        智能问数对话
        """
        system_prompt = "你是一个数据分析专家。请根据用户的问题，模拟查询数据库并给出专业的数据分析回答。"
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": message}
                ],
                temperature=0.7,
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"Error calling LLM: {e}")
            return f"调用大模型失败: {str(e)}。"

    def analyze_file(self, file_path: str) -> dict:
        """
        智能问数文件分析
        """
        filename = os.path.basename(file_path)
        file_content = ""
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                file_content = f.read(10000)
        except Exception:
            file_content = "(文件内容无法读取或非文本文件)"

        prompt = f"请分析以下文件内容（文件名：{filename}）：\n\n{file_content}\n\n请生成一份详细的分析报告。"
        
        try:
            # analysis_result = self.chat(prompt)
            analysis_result = "test"

        except Exception as e:
            analysis_result = f"分析失败: {str(e)}"

        output_dir = "outputs"
        os.makedirs(output_dir, exist_ok=True)
        
        result_filename = f"analysis_report_{filename}.txt"
        result_path = os.path.join(output_dir, result_filename)
        
        with open(result_path, "w", encoding="utf-8") as f:
            f.write(f"Analysis Report for {filename}\n")
            f.write("="*30 + "\n")
            f.write(f"Mode: Smart Query\n")
            f.write(f"Generated by: {self.model}\n")
            f.write("-" * 20 + "\n\n")
            f.write(analysis_result)
            
        return {
            "message": f"文件 {filename} 分析完成，请查看生成的报告。",
            "generated_file": {
                "name": result_filename,
                "path": result_path,
                "size": os.path.getsize(result_path)
            }
        }
