from openai import OpenAI
import os

class UnstructuredService:
    def __init__(self):
        # 配置 OpenAI 客户端
        self.client = OpenAI(
            base_url="https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
            api_key="sk-c13d96e9c2b0486bb3a2c2ed6016e9b5"
        )
        self.model = "qwen3-max" 

    def chat(self, message: str) -> str:
        """
        非结构化分析对话
        """
        system_prompt = "请记住你是一个非结构化文本分析专家。请对用户输入的内容进行深度解析和提炼。"
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": message}
                ],
                temperature=0.7,
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"Error calling LLM: {e}")
            return f"调用大模型失败: {str(e)}。"

    def analyze_file(self, file_path: str) -> dict:
        """
        非结构化文件分析
        """
        filename = os.path.basename(file_path)
        file_content = ""
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                file_content = f.read(10000)
        except Exception:
            file_content = "(文件内容无法读取或非文本文件)"

        prompt = f"请分析以下文件内容（文件名：{filename}）：\n\n{file_content}\n\n请生成一份详细的分析报告。"
        
        try:
            analysis_result = self.chat(prompt)
        except Exception as e:
            analysis_result = f"分析失败: {str(e)}"

        output_dir = "outputs"
        os.makedirs(output_dir, exist_ok=True)
        
        result_filename = f"analysis_report_{filename}.txt"
        result_path = os.path.join(output_dir, result_filename)
        
        with open(result_path, "w", encoding="utf-8") as f:
            f.write(f"Analysis Report for {filename}\n")
            f.write("="*30 + "\n")
            f.write(f"Mode: Unstructured Analysis\n")
            f.write(f"Generated by: {self.model}\n")
            f.write("-" * 20 + "\n\n")
            f.write(analysis_result)
            
        return {
            "message": f"文件 {filename} 分析完成，请查看生成的报告。",
            "generated_file": {
                "name": result_filename,
                "path": result_path,
                "size": os.path.getsize(result_path)
            }
        }

    def extract_data_from_file(self, file_path: str) -> dict:
        """
        非结构化信息提取
        """
        filename = os.path.basename(file_path)
        file_content = ""
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                file_content = f.read(10000)
        except Exception:
            file_content = "(文件内容无法读取或非文本文件)"

        prompt = f"请对以下文件内容（文件名：{filename}）进行非结构化信息提取。请将关键信息提取为结构化的格式（如JSON或Markdown表格），并忽略无关信息。\n\n内容：\n{file_content}"
        
        try:
            # 复用 chat 方法，但 prompt 是提取专用的
            extraction_result = self.chat(prompt)
        except Exception as e:
            extraction_result = f"提取失败: {str(e)}"

        output_dir = "outputs"
        os.makedirs(output_dir, exist_ok=True)
        
        result_filename = f"extraction_result_{filename}.txt"
        result_path = os.path.join(output_dir, result_filename)
        
        with open(result_path, "w", encoding="utf-8") as f:
            f.write(f"Extraction Result for {filename}\n")
            f.write("="*30 + "\n")
            f.write(f"Generated by: {self.model}\n")
            f.write("-" * 20 + "\n\n")
            f.write(extraction_result)
            
        return {
            "message": f"文件 {filename} 提取完成，请下载结果文件。",
            "generated_file": {
                "name": result_filename,
                "path": result_path,
                "size": os.path.getsize(result_path)
            }
        }
